openapi: 3.0.1
info:
  title: Product Service
  description: This service serves products.
  version: "1.0.0"
servers:
  - url: https://w2jwx3924e.execute-api.us-east-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: prod
paths:
  /products/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
    options:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: 204 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
  /:
    options:
      responses:
        "204":
          description: 204 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
  /products:
    get:
      responses:
        "200":
          description: Successful response
    options:
      responses:
        "204":
          description: 204 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
components: {}
